In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
#IMPORTING PACKAGES
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from matplotlib.pyplot import imread #READING IMAGE
%matplotlib inline


In [ ]:
#NATURAL LANGUAGE PROCESSING PACKAGES
import string # special operations on strings
import spacy # language models
import nltk #natural language tool kit
from wordcloud import WordCloud


/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [ ]:
# IMPORTING DATASET
book=pd.read_csv("/content/apple.txt",error_bad_lines=False)

<ipython-input-3-a2008eb34ee0>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  book=pd.read_csv("/content/apple.txt",error_bad_lines=False)
b'Skipping line 6: expected 1 fields, saw 14\n'


In [ ]:
book

x
0   It's amazing..... battery last around 10 -12 h...
1   Finally a MacBook possession. Got it in 50k in...
2   Best Laptop under 60k. If you don't want any a...
3   Pros:1. Light weight and super fast response t...
4                                                   "
5   I am very upset about the product as I checked...
6   Reason for 1 star is I ot an defective piece. ...
7   Got the Apple Macbook air on amazon discount s...
8   White line coming on screen in just three mont...
9   Bought this product recently on 5 April, was w...
10  Hi, Think thousand time before buying. One cal...
11  We buy macbook's expecting that it will lasts ...
12  I use this for music production and it works a...
13  Never purchase any Apple products. I bought 3 ...
14  Good purchase of mineBest for programming...On...
15  I bought MacBook air in 2017, it was working f...
16  Bought it on 9th July, stopped working / not t...
17  I bought it last year from Amazon during Sale....
18              All are Gud.. For now..\n            
19  Apple,apple,apple, thats the first thing that ...
20  After using Windows Operating system for the p...
21  MacBook Air is excellent. The build is super s...
22  Very handy laptop, light weight and portable. ...
23  I was apprehensive of buying Apple product fro...
24  I brought this mac air on sep 2017. From past ...
25  Don't want to mention anything for apple MAC b...
26  I have my worst nightmare with the macbook air...
27  Everything about this product seems to be fine...
28  I was looking for an affordable long lasting l...
29  This is the worst  apple product I have ever s...
30  Amazing product..it has quality written all ov...
31  From the very beginning the battery life was h...
32  The rating isn't for Apple's performance. I ex...
33  I preferred this over other good spec windows ...
34  When i received, within 15 days i realised the...
35  Be careful while buying electronic products th...
36  MERITS..IT IS BEST IN ITS PERFORMANCE..SOUND Q...
37  3 years and still running! great product\n    ...
38  The elegant work of apple can be seen in this ...
39  I got a great deal on this laptop, which I hav...

In [ ]:
book = [x.strip() for x in book.x] # remove both the leading and the trailing characters
book = [x for x in book if x] # removes empty strings, because they are considered in Python as False
book[0:10]

["It's amazing..... battery last around 10 -12 hrs.....best laptop for students and coders",
 "Finally a MacBook possession. Got it in 50k in Diwali sale. Technically good laptop.Good News.luxury product, niche technology, good battery life, reliable machine (other laptops crash and become defunct in 6-10 years), no anti-virus required, security of data and transactions much better. Terrific sense of possession & pride.Bad News. Problems will be there if you are switching from windows based system - very less space in hard disk, no CD drive, inability to transfer data from Mac to your existing external hard disc unless you format it, apps are mostly paid and re unreasonably expensive (no free apps which are available otherwise on google play store, even the angry bird costs Rs 400 !!), all printers are not compatible (e.g. the most economical MFD laser printer RICOH SP 111 can't be used), huge compatibility issues with Pages (MS Word) and Keynote (powerpoint) unless you master it by wo

In [ ]:
book

["It's amazing..... battery last around 10 -12 hrs.....best laptop for students and coders",
 "Finally a MacBook possession. Got it in 50k in Diwali sale. Technically good laptop.Good News.luxury product, niche technology, good battery life, reliable machine (other laptops crash and become defunct in 6-10 years), no anti-virus required, security of data and transactions much better. Terrific sense of possession & pride.Bad News. Problems will be there if you are switching from windows based system - very less space in hard disk, no CD drive, inability to transfer data from Mac to your existing external hard disc unless you format it, apps are mostly paid and re unreasonably expensive (no free apps which are available otherwise on google play store, even the angry bird costs Rs 400 !!), all printers are not compatible (e.g. the most economical MFD laser printer RICOH SP 111 can't be used), huge compatibility issues with Pages (MS Word) and Keynote (powerpoint) unless you master it by wo

In [ ]:
# Joining the list into one string/text
text = ' '.join(book)
text

'It\'s amazing..... battery last around 10 -12 hrs.....best laptop for students and coders Finally a MacBook possession. Got it in 50k in Diwali sale. Technically good laptop.Good News.luxury product, niche technology, good battery life, reliable machine (other laptops crash and become defunct in 6-10 years), no anti-virus required, security of data and transactions much better. Terrific sense of possession & pride.Bad News. Problems will be there if you are switching from windows based system - very less space in hard disk, no CD drive, inability to transfer data from Mac to your existing external hard disc unless you format it, apps are mostly paid and re unreasonably expensive (no free apps which are available otherwise on google play store, even the angry bird costs Rs 400 !!), all printers are not compatible (e.g. the most economical MFD laser printer RICOH SP 111 can\'t be used), huge compatibility issues with Pages (MS Word) and Keynote (powerpoint) unless you master it by worki

In [ ]:
#Punctuation
no_punc_text = text.translate(str.maketrans('', '', string.punctuation)) #with arguments (x, y, z) where 'x' and 'y'
# must be equal-length strings and characters in 'x'
# are replaced by characters in 'y'. 'z'
# is a string (string.punctuation here)
no_punc_text

'Its amazing battery last around 10 12 hrsbest laptop for students and coders Finally a MacBook possession Got it in 50k in Diwali sale Technically good laptopGood Newsluxury product niche technology good battery life reliable machine other laptops crash and become defunct in 610 years no antivirus required security of data and transactions much better Terrific sense of possession  prideBad News Problems will be there if you are switching from windows based system  very less space in hard disk no CD drive inability to transfer data from Mac to your existing external hard disc unless you format it apps are mostly paid and re unreasonably expensive no free apps which are available otherwise on google play store even the angry bird costs Rs 400  all printers are not compatible eg the most economical MFD laser printer RICOH SP 111 cant be used huge compatibility issues with Pages MS Word and Keynote powerpoint unless you master it by working on these still mostly the document and slides ei

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Tokenization
from nltk.tokenize import word_tokenize
text_tokens = word_tokenize(no_punc_text)
print(text_tokens[0:50])

['Its', 'amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'for', 'students', 'and', 'coders', 'Finally', 'a', 'MacBook', 'possession', 'Got', 'it', 'in', '50k', 'in', 'Diwali', 'sale', 'Technically', 'good', 'laptopGood', 'Newsluxury', 'product', 'niche', 'technology', 'good', 'battery', 'life', 'reliable', 'machine', 'other', 'laptops', 'crash', 'and', 'become', 'defunct', 'in', '610', 'years', 'no', 'antivirus', 'required', 'security', 'of']


In [ ]:
len(text_tokens)

3444

In [ ]:
#Remove stopwords
from nltk.corpus import stopwords

my_stop_words = stopwords.words('english')
my_stop_words.append('the')
my_stop_words.append('Its')

no_stop_tokens = [word for word in text_tokens if not word in my_stop_words]
print(no_stop_tokens[0:40])

['amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'students', 'coders', 'Finally', 'MacBook', 'possession', 'Got', '50k', 'Diwali', 'sale', 'Technically', 'good', 'laptopGood', 'Newsluxury', 'product', 'niche', 'technology', 'good', 'battery', 'life', 'reliable', 'machine', 'laptops', 'crash', 'become', 'defunct', '610', 'years', 'antivirus', 'required', 'security', 'data', 'transactions']


In [ ]:
#Normalize the data
lower_words = [x.lower() for x in no_stop_tokens]
print(lower_words[0:25])

['amazing', 'battery', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'students', 'coders', 'finally', 'macbook', 'possession', 'got', '50k', 'diwali', 'sale', 'technically', 'good', 'laptopgood', 'newsluxury', 'product', 'niche', 'technology', 'good']


In [ ]:
#Stemming
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stemmed_tokens = [ps.stem(word) for word in lower_words]
print(stemmed_tokens[0:40])

['amaz', 'batteri', 'last', 'around', '10', '12', 'hrsbest', 'laptop', 'student', 'coder', 'final', 'macbook', 'possess', 'got', '50k', 'diwali', 'sale', 'technic', 'good', 'laptopgood', 'newsluxuri', 'product', 'nich', 'technolog', 'good', 'batteri', 'life', 'reliabl', 'machin', 'laptop', 'crash', 'becom', 'defunct', '610', 'year', 'antiviru', 'requir', 'secur', 'data', 'transact']


In [ ]:
#!python -m spacy download en

In [ ]:
# NLP english language model of spacy library
nlp = spacy.load('en_core_web_sm')

In [ ]:
# lemmas being one of them, but mostly POS, which will follow later
doc = nlp(' '.join(no_stop_tokens))
print(doc[0:40])

amazing battery last around 10 12 hrsbest laptop students coders Finally MacBook possession Got 50k Diwali sale Technically good laptopGood Newsluxury product niche technology good battery life reliable machine laptops crash become defunct 610 years antivirus required security data transactions


In [ ]:
lemmas = [token.lemma_ for token in doc]
print(lemmas[0:25])

['amazing', 'battery', 'last', 'around', '10', '12', 'hrsb', 'laptop', 'student', 'coder', 'finally', 'MacBook', 'possession', 'get', '50k', 'Diwali', 'sale', 'technically', 'good', 'laptopgood', 'Newsluxury', 'product', 'niche', 'technology', 'good']


#### Feature Extraction

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(lemmas)

In [ ]:
pd.DataFrame.from_records([vectorizer.vocabulary_]).T.sort_values(0,ascending=False).head(20)

0
yrs          886
youtube      885
you          884
yes          883
yearsmy      882
year         881
yay          880
xcode        879
writer       878
write        877
woulnt       876
would        875
worst        874
working      873
work         872
wordmagsafe  871
wordkeynote  870
word         869
wonder       868
without      867

In [ ]:
print(vectorizer.vocabulary_)

{'amazing': 70, 'battery': 119, 'last': 459, 'around': 95, '10': 0, '12': 6, 'hrsb': 395, 'laptop': 452, 'student': 763, 'coder': 180, 'finally': 322, 'macbook': 491, 'possession': 613, 'get': 353, '50k': 34, 'diwali': 250, 'sale': 685, 'technically': 779, 'good': 358, 'laptopgood': 455, 'newsluxury': 543, 'product': 631, 'niche': 545, 'technology': 780, 'life': 469, 'reliable': 663, 'machine': 493, 'crash': 205, 'become': 123, 'defunct': 226, '610': 44, 'year': 881, 'antivirus': 81, 'require': 671, 'security': 698, 'datum': 217, 'transaction': 817, 'much': 533, 'well': 855, 'terrific': 785, 'sense': 704, 'pridebad': 623, 'news': 542, 'problem': 627, 'switch': 772, 'window': 862, 'base': 117, 'system': 773, 'less': 466, 'space': 738, 'hard': 375, 'disk': 245, 'cd': 166, 'drive': 255, 'inability': 409, 'transfer': 818, 'mac': 490, 'exist': 292, 'external': 304, 'disc': 243, 'unless': 825, 'format': 333, 'app': 84, 'mostly': 527, 'pay': 589, 'unreasonably': 826, 'expensive': 294, 'free':

In [ ]:
print(vectorizer.get_feature_names_out()[50:100])
print(X.toarray()[50:100])

['9th' 'able' 'accidental' 'accounting' 'act' 'adapt' 'add' 'adding'
 'additionaly' 'advantage' 'affordable' 'after' 'again' 'againcontacte'
 'ahead' 'air' 'all' 'almost' 'along' 'also' 'amazing' 'amazingnice'
 'amazon' 'amazoni' 'among' 'and' 'android' 'angle' 'angry' 'another'
 'answer' 'antivirus' 'anyone' 'anything' 'app' 'appario' 'apple'
 'appleappleapple' 'apples' 'application' 'apprehensive' 'appropriate'
 'appsnumber' 'april' 'arenot' 'around' 'ask' 'aspect' 'atleast' 'atomic']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(X.toarray().shape)

(2101, 887)


#### Let's see how can bigrams and trigrams can be included here

In [ ]:
vectorizer_ngram_range = CountVectorizer(analyzer='word',ngram_range=(1,3),max_features = 100)
bow_matrix_ngram =vectorizer_ngram_range.fit_transform(book)

In [ ]:
bow_matrix_ngram

<40x100 sparse matrix of type '<class 'numpy.int64'>'
	with 1014 stored elements in Compressed Sparse Row format>

In [ ]:
print(vectorizer_ngram_range.get_feature_names_out())
print(bow_matrix_ngram.toarray())

['about' 'after' 'air' 'all' 'am' 'amazon' 'an' 'and' 'any' 'apple' 'are'
 'around' 'as' 'at' 'battery' 'be' 'best' 'better' 'bought' 'but' 'buy'
 'can' 'cost' 'display' 'even' 'external' 'fine' 'for' 'from' 'get' 'good'
 'got' 'great' 'hard' 'have' 'if' 'if you' 'if you are' 'in' 'is' 'is not'
 'issues' 'it' 'it is' 'its' 'just' 'keyboard' 'laptop' 'like' 'mac'
 'macbook' 'macbook air' 'me' 'months' 'my' 'need' 'no' 'not' 'now' 'of'
 'of the' 'on' 'on this' 'one' 'only' 'or' 'other' 'product' 'quality'
 'sale' 'screen' 'service' 'service center' 'so' 'some' 'still' 'stopped'
 'that' 'the' 'then' 'they' 'this' 'to' 'using' 'very' 'want' 'want to'
 'warranty' 'was' 'which' 'while' 'will' 'windows' 'with' 'working'
 'would' 'year' 'years' 'you' 'you are']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 8 1]
 [1 0 0 ... 0 7 1]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 0]]


#### TFidf vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer_n_gram_max_features = TfidfVectorizer(norm="l2",analyzer='word', ngram_range=(1,3), max_features = 10)
tf_idf_matrix_n_gram_max_features =vectorizer_n_gram_max_features.fit_transform(book)
print(vectorizer_n_gram_max_features.get_feature_names_out())
print(tf_idf_matrix_n_gram_max_features.toarray())

['and' 'for' 'in' 'is' 'it' 'of' 'the' 'this' 'to' 'you']
[[0.55488769 0.63197542 0.         0.         0.54102376 0.
  0.         0.         0.         0.        ]
 [0.4706046  0.14617727 0.3003391  0.         0.25027991 0.20577568
  0.30721178 0.         0.36025074 0.58121993]
 [0.         0.61188088 0.13968713 0.         0.17460705 0.0717794
  0.06123583 0.         0.25132788 0.7096012 ]
 [0.69744641 0.2647797  0.         0.27201116 0.         0.55910086
  0.23848767 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.33002593 0.37587476 0.38614036 0.09653509 0.40222525 0.19842146
  0.50782685 0.1079973  0.34737573 0.        ]
 [0.17585656 0.20028742 0.20575751 0.41151502 0.34292552 0.21146045
  0.72159729 0.         0.18510151 0.        ]
 [0.27344413 0.         0.10664598 0.5332299  0.         0.21920373
  0.467513   0.         0.38375916 0.46436089]
 [0.         0.         0.34711306 0.  

####  Generate wordcloud

In [ ]:
# Import packages
import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS
# Define a function to plot word cloud
def plot_cloud(wordcloud):
    # Set figure size
    plt.figure(figsize=(40, 30))
    # Display image
    plt.imshow(wordcloud)
    # No axis details
    plt.axis("off");

In [ ]:
# Generate wordcloud
stopwords = STOPWORDS
stopwords.add('will')
stopwords.add('apple')
stopwords.add('Amazon')
stopwords.add('laptop')

wordcloud = WordCloud(width = 3000, height = 2000,
                      background_color='black', max_words=100,
                      colormap='Set2',stopwords=stopwords).generate(text)
# Plot
plot_cloud(wordcloud)

In [ ]:
# Save image
#wordcloud.to_file("wordcloud.png")